;;; Automatically generated by `recentf' on Mon Jan 16 00:27:05 2012.

(setq recentf-list
      '(
        "/usr/share/awesome/bashets/date.sh"
        "/usr/include/unistd.h"
        "/home/asido/src/awesome/awesome.c"
        "/home/asido/webs/property/search-results.php"
        "/home/asido/linux-2012.01-vanilla/kernel/irq/handle.c"
        "/home/asido/linux-2012.01-vanilla/fs/exec.c"
        "/home/asido/src/weechat-0.3.6/src/core/wee-proxy.c"
        "/home/asido/webs/lmlu/confirm.php"
        "/home/asido/webs/lmlu/adv.html"
        "/home/asido/webs/shenerhathaway/wp-content/themes/shener/thank-you.php"
        "/home/asido/webs/shenerhathaway/wp-content/themes/shener/loop-attachment.php"
        "/home/asido/src/awesome/lib/awful/wibox.lua.in"
        "/home/asido/src/awesome/screen.c"
        "/home/asido/src/awesome/draw.c"
        "/home/asido/src/awesome/color.c"
        "/home/asido/.emacs"
        "/home/asido/.emacs.d/elpa/archives/marmalade/archive-contents"
        "/home/asido/.emacs.d/elpa/archives/gnu/archive-contents"
        "/home/asido/.emacs.d/elpa/archives/ELPA/archive-contents"
        "/home/asido/webs/lilly/wp-app.php"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
